apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: faiss-pvc
  namespace: linkedin-search
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo   # GKE standard StorageClass
